import { useState, useEffect } from 'react';
import { Navbar } from '../../components/layout/Navbar';
import { Sidebar } from '../../components/layout/Sidebar';
import { Card, CardHeader } from '../../components/ui/Card';
import { showToast } from '../../components/ui/Toast';
import { useAuth } from '../../context/AuthContext';
import api from '../../api/axios';

export default function Preferences() {
  const { user } = useAuth();
  const [format, setFormat] = useState('excel');
  const [saving, setSaving] = useState(false);
  const [loading, setLoading] = useState(true);

  // Load the actual saved preference from the backend on mount
  useEffect(() => {
    api.get('/customer/preferences')
      .then(res => setFormat(res.preferred_bill_format || 'excel'))
      .catch(() => {
        // Fallback to default if error (e.g. not yet a customer)
        setFormat('excel');
      })
      .finally(() => setLoading(false));
  }, []);

  const handleSave = async () => {
    setSaving(true);
    try {
      await api.patch('/customer/preferences', { preferred_bill_format: format });
      showToast(`✓ Preference saved - bills will be sent as ${format.toUpperCase()}`);
    } catch (err) {
      showToast(err?.message || 'Failed to save preference', 'error');
    } finally {
      setSaving(false);
    }
  };

  return (
    <>
      <Navbar />
      <Sidebar />
      <main className="main-content">
        <div className="pg-hdr">
          <div>
            <div className="pg-title">Preferences</div>
            <div className="pg-sub">Manage your account settings and download preferences</div>
          </div>
        </div>

        <div style={{ maxWidth: 560 }}>
          <Card style={{ marginBottom: '1.25rem' }}>
            <CardHeader title="Bill download format" />
            <div style={{ padding: '1.25rem 1.5rem' }}>
              <p style={{ fontSize: 13, color: 'var(--text-2)', marginBottom: '1.25rem', lineHeight: 1.6 }}>
                Choose the file format you'd like to receive your bills in.
                Only this format will be generated and sent to you - saving storage and keeping things simple.
              </p>

              <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: '1.5rem' }}>
                {[
                  {
                    value: 'excel',
                    label: 'Excel (.xlsx)',
                    desc: 'Best for viewing, filtering, and printing. Compatible with Microsoft Excel and Google Sheets.',
                    icon: (
                      <svg viewBox="0 0 24 24" style={{ width: 22, height: 22, stroke: '#166534', fill: 'none', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' }}>
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/>
                      </svg>
                    ),
                    accent: '#166534', bg: 'var(--green-light)', border: 'rgba(22,101,52,.25)',
                  },
                  {
                    value: 'csv',
                    label: 'CSV (.csv)',
                    desc: 'Lightweight plain-text format. Ideal for importing into accounting or ERP software.',
                    icon: (
                      <svg viewBox="0 0 24 24" style={{ width: 22, height: 22, stroke: 'var(--blue)', fill: 'none', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' }}>
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/>
                        <line x1="8" y1="13" x2="16" y2="13"/><line x1="8" y1="17" x2="16" y2="17"/>
                      </svg>
                    ),
                    accent: 'var(--blue)', bg: 'var(--blue-light)', border: 'rgba(26,86,219,.2)',
                  },
                  {
                    value: 'pdf',
                    label: 'PDF (.pdf)',
                    desc: 'Standard uneditable format. Best for viewing as generated by the system.',
                    icon: (
                      <svg viewBox="0 0 24 24" style={{ width: 22, height: 22, stroke: 'var(--red)', fill: 'none', strokeWidth: 1.8, strokeLinecap: 'round', strokeLinejoin: 'round' }}>
                        <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14,2 14,8 20,8"/>
                        <path d="M9 15v-6h2a2 2 0 0 1 2 2v0a2 2 0 0 1 -2 2h-2"/>
                      </svg>
                    ),
                    accent: 'var(--red)', bg: 'var(--red-light)', border: 'rgba(220,38,38,.2)',
                  },
                ].map(opt => (
                  <label
                    key={opt.value}
                    onClick={() => setFormat(opt.value)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: 14,
                      padding: '1rem 1.25rem',
                      border: `1.5px solid ${format === opt.value ? opt.accent : 'var(--border)'}`,
                      borderRadius: 'var(--radius)',
                      background: format === opt.value ? opt.bg : 'var(--surface)',
                      cursor: 'pointer', transition: 'all .15s',
                    }}
                  >
                    <input
                      type="radio" name="format" value={opt.value}
                      checked={format === opt.value}
                      onChange={() => setFormat(opt.value)}
                      style={{ accentColor: opt.accent, width: 16, height: 16, flexShrink: 0 }}
                    />
                    <div style={{
                      width: 40, height: 40, borderRadius: 10,
                      background: format === opt.value ? opt.bg : 'var(--surface-2)',
                      border: `1px solid ${format === opt.value ? opt.border : 'var(--border)'}`,
                      display: 'flex', alignItems: 'center', justifyContent: 'center', flexShrink: 0,
                      transition: 'all .15s',
                    }}>
                      {opt.icon}
                    </div>
                    <div>
                      <div style={{ fontSize: 14, fontWeight: 600, color: format === opt.value ? opt.accent : 'var(--text)', marginBottom: 2 }}>
                        {opt.label}
                      </div>
                      <div style={{ fontSize: 12, color: 'var(--text-2)', lineHeight: 1.5 }}>
                        {opt.desc}
                      </div>
                    </div>
                    {format === opt.value && (
                      <div style={{ marginLeft: 'auto', flexShrink: 0 }}>
                        <svg viewBox="0 0 24 24" style={{ width: 18, height: 18, stroke: opt.accent, fill: 'none', strokeWidth: 2.5, strokeLinecap: 'round', strokeLinejoin: 'round' }}>
                          <polyline points="20,6 9,17 4,12"/>
                        </svg>
                      </div>
                    )}
                  </label>
                ))}
              </div>

              <div style={{
                background: 'var(--blue-light)', border: '1px solid rgba(26,86,219,.2)',
                borderRadius: 'var(--radius)', padding: '.75rem 1rem',
                fontSize: 12.5, color: '#1e40af', lineHeight: 1.6, marginBottom: '1.25rem',
              }}>
                💡 This preference is saved to your account. Your admin will automatically generate bills in this format for you - no need to convert files manually.
              </div>

              <button
                className="btn btn-primary"
                style={{ width: '100%', justifyContent: 'center', padding: 13 }}
                onClick={handleSave}
                disabled={saving}
              >
                {saving ? 'Saving…' : 'Save Preference'}
              </button>
            </div>
          </Card>
        </div>
      </main>
    </>
  );
}
